server {
    listen 80; # 컨테이너 내부에서 80번 포트를 사용합니다.
    server_name localhost;

    location / {
        root   /usr/share/nginx/html; # 빌드된 파일들이 복사될 경로입니다.
        index  index.html index.htm;
        # 중요: 어떤 경로로 들어와도 index.html로 보내서 리액트 라우팅이 작동하게 합니다.
        try_files $uri $uri/ /index.html;
    }
}