# [운영 환경(CI/CD 배포) 전용 설정]

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

file:
  upload-dir: /app/uploads/

logging:
  level:

    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.sql: ERROR
    org.hibernate.type.descriptor.sql: ERROR
