# [운영 환경(CI/CD 배포) 전용 설정]

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

  sql:
    init:
      mode: never


app:
  default-image-url: https://plant-parent-image-bucket.s3.ap-northeast-2.amazonaws.com/uploads/default_profile.jpg

logging:
  level:

    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.sql: ERROR
    org.hibernate.type.descriptor.sql: ERROR
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:plant-parent-image-bucket}
    region: ${AWS_S3_REGION:ap-northeast-2}
nongsaro:
  api: https://api.nongsaro.go.kr/service/garden
  key: ${NONGSARO_API_KEY}